"""Create a static release from an explicit allowlist; no dependency installation."""
import hashlib
import json
from pathlib import Path
import re
import shutil
from zipfile import ZipFile, ZIP_DEFLATED

root = Path(__file__).resolve().parents[1]
output = root / "dist" / "no-way-out"
marker = output / ".no-way-out-release"
if output.exists() and any(output.iterdir()) and not marker.exists():
    raise SystemExit("Refusing to replace an unmarked output directory")
if output.exists():
    shutil.rmtree(output)
output.mkdir(parents=True)
marker.write_text("Generated by scripts/build-release.py\n")
files = ["index.html", "editor.html", "icon.png", "README.md", "SURVIVAL_GUIDE.md", "CONTENT_REVIEW.md", "ENDING_CATALOG.md", "RELEASE_NOTES.md"]
files += [str(path.relative_to(root)) for directory in ["js", "css", "assets"] for path in sorted((root / directory).rglob("*")) if path.is_file()]
for name in files:
    source = root / name
    if not source.is_file():
        raise SystemExit(f"Required release file missing: {name}")
    destination = output / name
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, destination)
version = re.search(r"CONTENT_VERSION = '([^']+)'", (root / "js/content-manifest.js").read_text()).group(1)
manifest = {"contentVersion": version, "saveVersion": 2, "files": {name: {"bytes": (output / name).stat().st_size, "sha256": hashlib.sha256((output / name).read_bytes()).hexdigest()} for name in sorted(files)}}
(output / "release.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2)+"\n")
archive = output.parent / f"no-way-out-{version}.zip"
with ZipFile(archive, "w", ZIP_DEFLATED) as package:
    for path in sorted(output.rglob("*")):
        if path.is_file() and path != marker:
            package.write(path, path.relative_to(output))
print(f"Static directory: {output}")
print(f"Archive: {archive}")
print(f"Files: {len(files)}; source bytes: {sum(item['bytes'] for item in manifest['files'].values())}; archive bytes: {archive.stat().st_size}")
